### PR TITLE
add multiple days task support

### PR DESCRIPTION
**Pull request by mercury131**

### CODE REVIEW

**Comment by mercury131** [comment]
Hello! 
I added the functionality described in this issue - https://github.com/Kartones/flask-calendar/issues/24

**Comment by Kartones** [comment]
Hi @mercury131 I guess you closed it because you want to iterate further on the pull request?

Feel free to reopen, or open a new one once ready :smiley:

**Comment by mercury131** [comment]
I closed it by mistake :) 
It will be possible to look at my code, maybe it will be useful

**Comment by Kartones** [comment]
perfect, I'll take a look as soon as I can, thank you!

**Review by Kartones — APPROVED** [review]
I'll apply some naming changes after the merge, but thanks! Simple and creative solution to implement the feature :+1:

**Pull request merged**
